// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// This file is generated by backend/scripts/sync-models-config.py
// To update models, edit backend/scripts/config.py and run sync-models-config.py

export interface BedrockModel {
  id: string
  name: string
  displayName: string
  description: string
  cost: string
  speed: string
  inferenceProfile: string | null
  available: boolean
  supportedModes: ('chat' | 'agent')[]
}

export const BEDROCK_MODELS: Record<string, BedrockModel> = {
  "nova-micro": {
    "id": "amazon.nova-micro-v1:0",
    "name": "Amazon Nova Micro",
    "displayName": "Nova Micro",
    "description": "Fast, lightweight model (free tier eligible)",
    "cost": "low",
    "speed": "fast",
    "inferenceProfile": null,
    "available": true,
    "supportedModes": [
      "chat"
    ]
  },
  "nova-premier": {
    "id": "amazon.nova-premier-v1:0",
    "name": "Amazon Nova Premier",
    "displayName": "Nova Premier",
    "description": "Improved quality Nova model",
    "cost": "medium",
    "speed": "medium",
    "inferenceProfile": "arn:aws:bedrock:us-east-1::inference-profile/us.amazon.nova-premier-v1:0",
    "available": true,
    "supportedModes": [
      "chat"
    ]
  },
  "claude-3-7-sonnet": {
    "id": "anthropic.claude-3-7-sonnet-20250219-v1:0",
    "name": "Claude 3.7 Sonnet",
    "displayName": "Claude 3.7 Sonnet",
    "description": "Premium quality model, highest cost",
    "cost": "highest",
    "speed": "medium",
    "inferenceProfile": "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
    "available": true,
    "supportedModes": [
      "chat"
    ]
  },
  "claude-4-sonnet": {
    "id": "anthropic.claude-sonnet-4-20250514-v1:0",
    "name": "Claude 4 Sonnet",
    "displayName": "Claude 4 Sonnet",
    "description": "Latest Claude Sonnet model",
    "cost": "highest",
    "speed": "medium",
    "inferenceProfile": "us.anthropic.claude-sonnet-4-20250514-v1:0",
    "available": true,
    "supportedModes": [
      "chat",
      "agent"
    ]
  },
  "claude-4-opus": {
    "id": "anthropic.claude-opus-4-20250514-v1:0",
    "name": "Claude 4 Opus",
    "displayName": "Claude 4 Opus",
    "description": "Most capable Claude model",
    "cost": "highest",
    "speed": "slow",
    "inferenceProfile": "arn:aws:bedrock:us-east-1::inference-profile/us.anthropic.claude-opus-4-20250514-v1:0",
    "available": true,
    "supportedModes": [
      "chat"
    ]
  }
}

export const getAvailableModels = (mode: 'chat' | 'agent' | 'all' = 'all'): BedrockModel[] => {
  return Object.entries(BEDROCK_MODELS)
    .filter(([_, model]) => {
      if (mode === 'all') return model.available
      return model.available && model.supportedModes.includes(mode)
    })
    .map(([key, model]) => ({ ...model, key }))
}

export const getDefaultModel = (mode: 'chat' | 'agent'): string => {
  return mode === 'agent' ? 'claude-4-sonnet' : 'claude-4-sonnet'
}

export const AGENT_MODEL_NOTE = 'Note: Agent mode uses Claude 4 Sonnet. Model selection in agent mode is for display only - the actual model is configured in AWS Console.'
