name: Sync Figma Design Tokens

on:
  # Manual trigger
  workflow_dispatch:
  
  # Run daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  
  # Run on pushes to main that modify Figma config
  push:
    branches: [main, amplify-production-ready]
    paths:
      - 'lib/figma/**'
      - '.github/workflows/figma-sync.yml'

jobs:
  sync-tokens:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install

      - name: Sync Figma tokens
        env:
          FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
        run: |
          pnpm tsx scripts/sync-figma-tokens.ts

      - name: Check for changes
        id: check-changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: sync design tokens from Figma'
          title: '[Automated] Sync Design Tokens from Figma'
          body: |
            ## 🎨 Design Token Sync
            
            This PR updates the design tokens from Figma.
            
            ### Changes
            - Updated colors, typography, spacing, and other design tokens
            - See `figma-sync-report.json` for details
            
            ### Next Steps
            1. Review the changes in `lib/brand/constants.ts`
            2. Test the visual changes locally
            3. Merge if everything looks good
            
            _This PR was automatically generated by the Figma sync workflow._
          branch: figma-sync/${{ github.run_number }}
          delete-branch: true
          labels: |
            design-system
            automated 